---
competition_name: "Cyberlandslaget 2023 | Attack-Defense"
# dates in UTC, Vienna local time is 2h later
services_public: '2020-00-00 00:00:00+00'
event_start:     '2023-00-00 00:00:00+00'
event_freeze:    '2024-00-00 00:00:00+00'
event_end:       '2025-00-00 00:00:00+00'
tick_duration: 60 # TODO change
valid_ticks: 5 # NOTE: changing this value also requires adjusting the checkerlib and the scoreboard
flag_prefix: 'CYBL_'

gamedb_host: gameserver-postgres
pgpassword: 9iyzXY6pMYzRvXZi

game_servicegroups:
- {id: 1, name: "Service 1", slug: "service1"}
- {id: 2, name: "Service 2", slug: "service2"}
- {id: 3, name: "Service 3", slug: "service3"}
- {id: 4, name: "Service 4", slug: "service4"}
- {id: 5, name: "Service 5", slug: "service5"}
- {id: 6, name: "Service 6", slug: "service6"}

game_services:
- {id:  1, group: 1, name: "Service 1 Checker 1", slug: "service1_checker1"}

- {id:  2, group: 2, name: "Service 2 Checker 1", slug: "service2_checker1"}
- {id:  3, group: 2, name: "Service 2 Checker 2", slug: "service2_checker2"}
- {id:  4, group: 2, name: "Service 2 Checker 3", slug: "service2_checker3"}

- {id:  5, group: 3, name: "Service 3 Checker 1", slug: "service3_checker1"}
- {id:  6, group: 3, name: "Service 3 Checker 2", slug: "service3_checker2"}
- {id:  7, group: 3, name: "Service 3 Checker 3", slug: "service3_checker3"}

- {id:  8, group: 4, name: "Service 4 Checker 1", slug: "service4_checker1"}
- {id:  9, group: 4, name: "Service 4 Checker 2", slug: "service4_checker2"}

- {id: 10, group: 5, name: "Service 5 Checker 1", slug: "service5_checker1"}
- {id: 11, group: 5, name: "Service 5 Checker 2", slug: "service5_checker2"}

- {id: 12, group: 6, name: "Service 6 Checker 1", slug: "service6_checker1"}
- {id: 13, group: 6, name: "Service 6 Checker 2", slug: "service6_checker2"}

teams: # TODO replace passwords with proper ones
  - {id: 1337, name: 'admin'                        , email: 'admin@example.com',  pass: 'admin',  logo: '', admin: True}
  - {id:    1, name: 'nop'                          , email: 'team01@example.com', pass: 'nop',    logo: '', nop: True}
  - {id:    2, name: 'Norway'                       , email: 'team02@example.com', pass: 'team02', logo: '/assets/flags/NO.svg'}
  - {id:    3, name: 'Sweden'                       , email: 'team03@example.com', pass: 'team03', logo: '/assets/flags/SE.svg'}
  - {id:    4, name: 'Denmark'                      , email: 'team04@example.com', pass: 'team04', logo: '/assets/flags/DK.svg'}